# Generated by Django 3.0.2 on 2020-02-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_avilable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.DecimalField(decimal_places=2, max_digits=3, max_length=5),
        ),
    ]
