# Generated by Django 3.0.2 on 2020-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_auto_20200201_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True, verbose_name='valid email address'),
            preserve_default=False,
        ),
    ]
