# Generated by Django 3.0.2 on 2020-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_fruit_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='valid email address'),
        ),
    ]
