# Generated by Django 3.0.2 on 2020-02-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0002_auto_20200202_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
    ]
